version: "3"

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/app/src/config.ts
      - ./wppconnect_tokens:/app/src/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}      